// EDITE AQUI SOMENTE OS PACOTES QUE DESEJA INSTALAR NO PROJETO
const pacotes = [
    'nodemon --save-dev',
    'prisma@7.3.0 --save-dev',
    '@prisma/adapter-pg@7.3.0',
    '@prisma/client@7.3.0',
    'dotenv',
    'express',
    'pg',
];

/*
 * NÃO EDITE DAQUI PARA BAIXO
 */
const apagar = {
    primeiro: ['inicial.js'],
    segundo: ['support.js', 'amods.js'],
};

const pacotesObrigatorios = [];

const criarItens = {
    '.gitignore': {
        codigo: `node_modules/
.env
dist/
build/
*.log
.DS_Store
prisma/migrations/`,
    },

    'package.json': {
        codigo: `{
  "name": "NOME_DA_PASTA",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "test": "echo \\"Error: no test specified\\" && exit 1",
    "dev": "nodemon src/server.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT"
}`,
    },

    'ReadMe.MD': {
        codigo: `# 1. Criar projeto
- npm init -y

# 2. Ajustar package.json
- Adicionar: "type": "module"
- Adicionar: "main": "server.js"
- Adicionar dentro do script: "dev": "nodemon server.js"

# 3. Instalar dependência
- npm i express dotenv pg @prisma/client @prisma/adapter-pg
- npm i -D nodemon prisma

# 4. Inicializar Prisma
- npx prisma init --datasource-provider postgresql

# 5. Configurar \`.env\`
- DATABASE_URL="postgresql://usuario:senha@localhost:porta/nome_do_banco_db"

# 6. Configurar schema.prisma
- crie suas tabelas

# 7. Gerar SQL
- npx prisma migrate dev --name init
- npx prisma generate

# 8. Semear dados no banco
- npx prisma db seed

# 9. Abrir Prisma Studio
- npx prisma studio

## Casos de erros

### Após alterar schema.prisma
- npx prisma migrate dev --name nome_da_alteracao (exemplo: adicionar_tabela_users)

### Banco inconsistente (⚠️ APAGA TUDO)
- npx prisma migrate reset

### Apenas popular dados
- npx prisma db seed

### Dicas
|   Comando       | Apaga dados?    | Cria migrations? | Uso            |
| --------------- | ------------    | ---------------- | -------------- |
| \`migrate dev\`   | ❌ Não          | ✅ Sim          | Alterar schema |
| \`db seed\`       | ❌ Não          | ❌ Não          | Popular dados  |
| \`migrate reset\` | ✅ SIM          | ❌ Não          | DEV only       |`,
    },

    '.env': {
        codigo: `DATABASE_URL="postgresql://usuario:senha@localhost:porta/nomeBanco_db"
PORT=3000`,
    },

    'prisma.config.js': {
        codigo: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: 'node prisma/seed.js',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});`,
    },

    prisma: {
        'schema.prisma': {
            codigo: `generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
}

model Exemplo {
    id        Int      @id @default(autoincrement())
    nome      String
    descricao String?
    ano       Int
    preco     Float
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt

    @@map("exemplo")
}`,
        },
        'seed.js': {
            codigo: `import 'dotenv/config';
import pkg from '@prisma/client';
const { PrismaClient } = pkg;
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
    console.log('🌱 Iniciando seed...');

    await prisma.exemplo.createMany({
        data: [
            { nome: 'Notebook Dell', descricao: 'Core i7', ano: 2023, preco: 3500.0 },
            { nome: 'Monitor LG', descricao: '27 polegadas', ano: 2024, preco: 1800.0 },
            { nome: 'Webcam Logitech', descricao: 'Full HD', ano: 2022, preco: 280.0 },
        ],
    });

    console.log('✅ Seed concluído!');
}

main()
    .catch((e) => {
        console.error('❌ Erro no seed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });`,
        },
    },

    src: {
        'server.js': {
            codigo: `import express from 'express';
import 'dotenv/config';
import exemplosRoutes from './routes/exemploRoute.js';

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {
    res.send('🚀 API funcionando');
});

// Rotas
app.use('/api', exemplosRoutes);

app.use((req, res) => {
    res.status(404).json({ error: 'Rota não encontrada' });
});

app.listen(PORT, () => {
    console.log(\`🚀 Servidor rodando em http://localhost:\${PORT}\`);
});`,
        },

        utils: {
            'prismaClient.js': {
                codigo: `import pkg from '@prisma/client';
const { PrismaClient } = pkg;
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import 'dotenv/config';

const pool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

export default prisma;`,
            },
        },

        models: {
            'exemploModel.js': {
                codigo: `import prisma from '../utils/prismaClient.js';

export const create = async (data) => {
    return await prisma.exemplo.create({ data });
};

export const findAll = async (filters = {}) => {
    const { nome, descricao, ano, preco } = filters;
    const where = {};

    if (nome) where.nome = { contains: nome, mode: 'insensitive' };
    if (descricao) where.descricao = { contains: descricao, mode: 'insensitive' };
    if (ano !== undefined) where.ano = parseInt(ano);
    if (preco !== undefined) where.preco = parseFloat(preco);

    return await prisma.exemplo.findMany({
        where,
        orderBy: { createdAt: 'desc' },
    });
};

export const findById = async (id) => {
    return await prisma.exemplo.findUnique({
        where: { id: parseInt(id) },
    });
};

export const update = async (id, data) => {
    return await prisma.exemplo.update({
        where: { id: parseInt(id) },
        data,
    });
};

export const remove = async (id) => {
    return await prisma.exemplo.delete({
        where: { id: parseInt(id) },
    });
};`,
            },
        },

        controllers: {
            'exemploController.js': {
                codigo: `import * as model from '../models/exemploModel.js';

export const getAll = async (req, res) => {
    try {
        const exemplos = await model.findAll(req.query);

        if (!exemplos || exemplos.length === 0) {
            return res.status(200).json({
                message: 'Nenhum registro encontrado.',
            });
        }
        res.json(exemplos);
    } catch (error) {
        console.error('Erro ao buscar:', error);
        res.status(500).json({ error: 'Erro ao buscar registros' });
    }
};

export const create = async (req, res) => {
    try {
        if (!req.body || Object.keys(req.body).length === 0) {
            return res.status(400).json({
                error: 'Corpo da requisição vazio. Envie os dados do exemplo!',
            });
        }

        const { nome, descricao, ano, preco } = req.body;

        if (!nome) return res.status(400).json({ error: 'O nome (nome) é obrigatório!' });
        if (!ano) return res.status(400).json({ error: 'O ano (ano) é obrigatório!' });
        if (!preco) return res.status(400).json({ error: 'O preço (preco) é obrigatório!' });

        const data = await model.create({
            nome,
            descricao,
            ano: parseInt(ano),
            preco: parseFloat(preco),
        });

        res.status(201).json({
            message: 'Registro cadastrado com sucesso!',
            data,
        });
    } catch (error) {
        console.error('Erro ao criar:', error);
        res.status(500).json({ error: 'Erro interno no servidor ao salvar o registro.' });
    }
};

export const getById = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) {
            return res.status(400).json({ error: 'O ID enviado não é um número válido.' });
        }

        const data = await model.findById(id);
        if (!data) {
            return res.status(404).json({ error: 'Registro não encontrado.' });
        }
        res.json({ data });
    } catch (error) {
        console.error('Erro ao buscar:', error);
        res.status(500).json({ error: 'Erro ao buscar registro' });
    }
};

export const update = async (req, res) => {
    try {
        const { id } = req.params;

        if (!req.body || Object.keys(req.body).length === 0) {
            return res.status(400).json({
                error: 'Corpo da requisição vazio. Envie os dados do exemplo!',
            });
        }

        if (isNaN(id)) return res.status(400).json({ error: 'ID inválido.' });

        const exists = await model.findById(id);
        if (!exists) {
            return res.status(404).json({ error: 'Registro não encontrado para atualizar.' });
        }

        const data = await model.update(id, req.body);
        res.json({
            message: \`O registro "\${data.nome}" foi atualizado com sucesso!\`,
            data,
        });
    } catch (error) {
        console.error('Erro ao atualizar:', error);
        res.status(500).json({ error: 'Erro ao atualizar registro' });
    }
};

export const remove = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) return res.status(400).json({ error: 'ID inválido.' });

        const exists = await model.findById(id);
        if (!exists) {
            return res.status(404).json({ error: 'Registro não encontrado para deletar.' });
        }

        await model.remove(id);
        res.json({
            message: \`O registro "\${exists.nome}" foi deletado com sucesso!\`,
            deletado: exists,
        });
    } catch (error) {
        console.error('Erro ao deletar:', error);
        res.status(500).json({ error: 'Erro ao deletar registro' });
    }
};`,
            },
        },

        routes: {
            'exemploRoute.js': {
                codigo: `import express from 'express';
import * as controller from '../controllers/exemploController.js';

const router = express.Router();

router.post('/exemplos', controller.create);
router.get('/exemplos', controller.getAll);
router.get('/exemplos/:id', controller.getById);
router.put('/exemplos/:id', controller.update);
router.delete('/exemplos/:id', controller.remove);

export default router;`,
            },
        },
    },
};

export { pacotesObrigatorios, pacotes, criarItens, apagar };
